# 推荐使用 yml 文件，比 properties 文件易于编写
# 有一个不好的就是，格式要求严谨，否则配置将读取不到导致配置异常。
name: Kode-sample-project
desc: ${name}, perfect!
test: I'm test value from application.properties.

server:
  port: 8000 # 服务端口，用来和 tomcat 默认端口区分

# 在配置文件中的读取，从自动装配的库中查找默认配置，然后覆盖默认配置的值
spring:
  freemarker:
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    template-loader-path:
      - classpath:/views/
    settings:
      datetime_format: yyyy/MM/dd HH:mm:ss

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_mybatis
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

