# 推荐使用 yml 文件，比 properties 文件易于编写
# 有一个不好的就是，格式要求严谨，否则配置将读取不到导致配置异常。
name: Kode-sample-project
desc: ${name}, perfect!
test: I'm test value from application.properties.

server:
  port: 8000 # 服务端口，用来和 tomcat 默认端口区分

# 在配置文件中的读取，从自动装配的库中查找默认配置，然后覆盖默认配置的值
spring:
  freemarker:
    # 设置模版加载路径
    templateLoaderPath:
      - classpath:/views/
      # 这样的配置只能在使用 gradle 内的插件时才能生效。
      # 很好理解，因为这部分资源文件只有在经过 gradle 处理之后才会被复制到 classpath下，才能被解析到。
      # 如果直接运行 main 方法入口是不能解析该文件夹内的页面的。
      # - webapp/views/

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_mybatis
    username: root
    password: root

